### ISSUE TITLE
How do I look at an entire single file through revisions?

### ISSUE THREAD

**Issue by kaihendry** [jonas/tig#1171]
https://stackoverflow.com/questions/69954683/how-do-i-look-at-a-file-across-revisions

**Comment by kaihendry** [comment]
I made a video describing my issue: https://s.natalian.org/2021-12-01/git-file.mp4

**Comment by koutcher** [comment]
The reason you can't get `f` to work is probably because your cursor in the diff view is not in the diff stat or in a diff chunk as indicated in #1006. Note that if you open a split diff view, you have to use `j` and `k` to move the cursor in the lower pane.
Someone may come with a better solution but I doubt it.
