### ISSUE TITLE
Unexpected author abbreviations when restoring from background

### ISSUE THREAD

**Issue by stuarthicks** [jonas/tig#232]
Using tig 1.2.1 (Nov 22 2013) on OSX 10.8.5, iTerm 2 and zsh.

Steps.
1. Launch tig
2. Press Up arrow (message appears on screen to say you cannot move above the top row)
3. Press ctrl-z to suspend tig
4. Bring tig back to the foreground with `fg`
5. Press Up arrow again

Expected: To see message on screen again about being at the top of the list.
Actual: Author field becomes abbreviated.

This can be repeated to un-abbreviate the author field. So I presume calling a toggleAuthorAbbreviation function somehow.

Also observed, immediately after restoring from background, I have to press the down arrow twice to go down. Are key mappings offset/incorrect in this state?

**Comment by igoralmeida** [comment]
I think a similar problem happens if you suspend $EDITOR while editing a commit message. Only tested with vim+bash:

1. In the status view, have some changes ready and press `C` to start a commit
1. Press `control-z` to suspend, shell shows up. Run `fg` to get vim back to foreground.
1. Finish the commit message, save and quit. Commit output is shown, press enter and tig shows up again.
1. Screen is not updated, it seems: keys pressed are just printed to the statusbar. I type `q<CR>` as many times as necessary to quit tig at this point.

**Comment by commonquail** [comment]
I can't reproduce @stuarthicks' issue on 4b0aba8 ("erase status line at exit time") but I traced @igoralmeida's issue to 83df6c3 ("Remove unneeded calls to {def,reset}_prog_mode"). It's consistently reproducible and it's not necessary write or save anything. Reverting that commit restores editor suspension capability, however, when eventually quitting tig the terminal screen doesn't clear like it normally does (and like `top` vs `htop`); same behaviour as in tig 2.0.1.

**Comment by jonas** [comment]
@commonquail Thanks for tracking down the commits. I reproduced @igoralmeida 's issue with the latest version and managed to come up with #657 to fix that.

**Comment by jonas** [comment]
Helped by @rolandwalker 's work in #665 and 167d59ed1474e10ec3310fe7aa77314247332954 I believe I finally found a fix for the initial issue also.

**Comment by stuarthicks** [comment]
@jonas @rolandwalker Thanks! 😄
