### ISSUE TITLE
Add support for diff-highlight

### ISSUE THREAD

**Issue by dwijnand** [jonas/tig#313]
I would be really nice if tig supported [diff-highlight](https://github.com/git/git/tree/v2.3.5/contrib/diff-highlight).

**Comment by dwijnand** [comment]
So.. I was wondering- how viable is including this? Is it possible to "shell out to perl" for this?

I've negligible experience in C, so I could use any help I can get in implementing this.

Thanks

**Comment by jonas** [comment]
There's two things required to make this work. First, the diff view will
need to learn how to parse ASCII control characters. To start with, only
the ones to enter/exit highlighting are required. Since the diff view is
line-based, `struct line` will need a flag to indicate whether `diff_draw`
needs to "interpret" the line characters.

Next, is the actual running of `diff-highlight` as a sort of filter of the
underlying `git-diff`/`git-show` command. Tig will need to set up the pipe
using the IO module. And also have hooks to kill/close the filter process.
It is not supported right now.

**Comment by danielmanesku** [comment]
It would be really nice to have this feature (or even better [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy#screenshot)), it saves a lot of time.
It also got some light from git team: https://github.com/blog/2188-git-2-9-has-been-released

**Comment by tqmz** [comment]
Would be nice indeed.

**Comment by wikimatze** [comment]
+1 for that feature

**Comment by jonas** [comment]
<img width="532" alt="screen shot 2016-11-07 at 00 29 31" src="https://cloud.githubusercontent.com/assets/8417/20047361/620ccf7c-a481-11e6-8e43-ffe00a76afe5.png">

**Comment by dwijnand** [comment]
What am I doing wrong that I see the following?

![image](https://cloud.githubusercontent.com/assets/344610/20051025/9f0edb20-a4c4-11e6-92ad-6ab51dcc4d0a.png)

**Comment by jonas** [comment]
How did you configure it?
```
09:17:19 /opt/tig#master > head $(which diff-highlight)
#!/usr/bin/perl

use 5.008;
use warnings FATAL => 'all';
use strict;

# Highlight by reversing foreground and background. You could do
# other things like bold or underline if you prefer.
my @OLD_HIGHLIGHT = (
	color_config('color.diff-highlight.oldnormal'),
09:17:33 /opt/tig#master > grep diff-highlight ~/.tigrc
set diff-highlight = true
```
Right now it only understands the standout terminal escape codes used by an "unconfigured" diff-highlight so did you configure anything under `color.diff-highlight`, i.e. what is the output of `git config -l | grep diff-highlight`? I might have to set `GIT_CONFIG` to remove such settings.

**Comment by dwijnand** [comment]
yeah I seem to have configured things under `color.diff-highlight`:

```
$ git config -l | grep diff-highlight
color.diff-highlight.oldnormal=red bold
color.diff-highlight.oldhighlight=red bold 52
color.diff-highlight.newnormal=green bold
color.diff-highlight.newhighlight=green bold 22
core.pager=diff-highlight | less -$LESS -F -x1,5 -X
interactive.difffilter=diff-highlight
```

**Comment by jonas** [comment]
@dwijnand OK, thanks, reproduced. I am new to diff-highlight so it's great to learn some tricks. I pushed a new commit to fix this so that it works _without_ support for colors. Will add tests for this when I have some time.

Implementing full support for terminal color escape codes would be nice but I think it would be better to support git's porcelain diff format which would open the doors to have split diff view, color words etc.

**Comment by dwijnand** [comment]
@jonas thanks!

**Comment by gweodoo** [comment]
@jonas I have some trouble with your awesome `diff-highlight` feature.
I'm building tig from `master` branch (dfa26fd) and also git from `master` branch (be5a750 --> 2.11.0-rc0+).
I'm enabling the capability from `.gitconfig` file: `[tig]   diff-highlight = true`

But I have this kind of weird stuff in the diff view:
![tig](https://cloud.githubusercontent.com/assets/2736934/20094607/55a6c270-a5a2-11e6-9198-c385413a4bdc.png)

As you mentioned, I've checked that i'm using Git's diff-highlight without any configuration.
I've also tried with an older version of git and specifying the option in .gitrc directly instead of .gitconfig, but none of them solve my issue.

Do you have any idea ? 
Thanks.

**Comment by jonas** [comment]
@gweodoo Do you have the diff-highlight script in your PATH?

**Comment by jonas** [comment]
@gweodoo I think (hope) that @dtwlin just fixed the issue you reported.

**Comment by tqmz** [comment]
Confirming this works nicely. Thanks so much!

_(Revision: e59bec54148f7bbef38929ebb7e0d865f1a1cb8b, tigrc: `set diff-highlight = true` with `diff-highlight` in `$PATH`.)_

**Comment by Liooo** [comment]
Can we use [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) now?

**Comment by jonas** [comment]
@Liooo No, not yet. With the infra put in place it should be doable. Do you mind creating a ticket for this?

**Comment by Liooo** [comment]
@jonas of course not!

**Comment by danielmanesku** [comment]
I can confirm that this works in tig 2.2.1, but only when used directly from terminal (iTerm2 for instance). 
When I am within tmux (2.2), the pieces are not highlighted. Tested with empty tmux.conf, and the issue still reproduces. Does anybody have it working within tmux?

**Comment by jonas** [comment]
I suggest opening a separate issue. I don't use tmux myself so
contributions in that regard would very appreciated.

**Comment by danielmanesku** [comment]
Issue #559 created. 
Somehow I got the feeling that everyone is using either tmux or screen, but seems that I was wrong.

**Comment by kadrach** [comment]
@danielmanesku No idea how I'd go about troubleshooting it, but it works perfectly well in tmux for me.

**Comment by gweodoo** [comment]
@jonas I'm sorry, I'm quite a bit late to respond (almost 5 months)
Indeed, with the fix you mentioned, everything goes well now !
tig being updated automatically twice a week with the master branch, I forgot to check.

Thanks !

**Comment by mapad** [comment]
For those who installed tig with the HomeBrew command 'brew install tig' on MacOs, you need before to install git through 'brew install git', otherwise it will use git default MacOS version which somehow doesn't play nicely with tig

**Comment by keimlink** [comment]
Works on macOS after `brew upgrade tig`, but I had to remove the default configuration in `/usr/local/etc/tigrc` so that the new default values are used. Otherwise the diff doesn't use the right colors, because they we not defined previously.

**Comment by frouo** [comment]
What is the better way to get `diff-highlight` installed on macOS? For the moment I have git installed though xcode-install (because I am iOS developer). I understand I have to install git via `brew install git` but I would rather not have 2 versions of git on my mac.

Thank you 🙏🏻

**Comment by koutcher** [comment]
Installing git via `brew install git` just to get `diff-highlight` would be a little overkill. If the Xcode version of git doesn't come with the contrib directory, just grab the `diff-highlight` script from `/usr/local/opt/git/share/git-core/contrib/diff-highlight` on another machine and put it somewhere in your PATH. If you don't have access to another machine, https://raw.githubusercontent.com/git/git/3dbfe2b8ae94cbdae5f3d32581aedaa5510fdc87/contrib/diff-highlight/diff-highlight should be good enough (it was the version before it was split in modules).

**Comment by frouo** [comment]
Thank you so much @koutcher ! 

For others with git installed though Xcode, here are the steps to "install" `diff-highlight`: 

1. Download the diff-highlight script and put the result in the file `/usr/local/bin/diff-highlight`:
```
curl -o /usr/local/bin/diff-highlight https://raw.githubusercontent.com/git/git/3dbfe2b8ae94cbdae5f3d32581aedaa5510fdc87/contrib/diff-highlight/diff-highlight
```

2. Make the file executable:
```
chmod +x /usr/local/bin/diff-highlight
```

3. Add diff-highlight in your PATH (or `~/.bash_profile` if using bash):
```
echo 'export PATH="$PATH:/usr/local/bin/diff-highlight"' >> ~/.zshrc
```

4. Do not forget to run `source` command to update your PATH in your current terminal:
```
source ~/.zshrc
```
