### ISSUE TITLE
Problem with encoding still exists on Mac OS X and Debian

### ISSUE THREAD

**Issue by jonas** [jonas/tig#330]
From user: I still have this issue. Installed on mac with brew, apt-get on deb stable. Screenshot along.

![screen shot 2014-09-16 at 12 07 55 am](https://cloud.githubusercontent.com/assets/601714/4276683/75782bbc-3d07-11e4-963b-b43ff00b465e.png)

References #72

**Comment by edi9999** [comment]
Using

```
LDLIBS = -lncursesw
CPPFLAGS = -DHAVE_NCURSESW_CURSES_H
```

in my config.make solves that issue. Great :-)

**Comment by guyzmo** [comment]
I have to add that the issue is still there with both v2.2 and `-git` versions on archlinux. When setting up the utf-8 formatting option in the `tigrc` it's working fine, with the neat `●─╮` or `●─┴─╯`. So ncursew is definitely there and working (even though it's being installed simply as ncurses).

## To reproduce

```
% git init test
% cd test
% touch fubar
% git add fubar
% git ci -m "this part is visible 😀🍻 this part is not visible ☹🔥"
% git log --oneline
9b66f84 this part is visible 😀🍻 this part is not visible ☹🔥
% tig
…
```
![screenshot from 2016-11-27 16-21-08](https://cloud.githubusercontent.com/assets/254441/20649328/9bddbd14-b4bd-11e6-844f-9061eb271709.png)

## Related

* in the archlinux tracker there's an issue about [ncursesw](https://bugs.archlinux.org/task/25482)
  * maybe is it a matter that there needs to be `HAVE_NCURSESW_CURSES_H` enabled with `ncursesw/curses.h` available on the system for the unicode log lines to be parsed correctly?
* there's been no report of [unicode issues otherwise](https://bugs.archlinux.org/?project=5&cat[]=33&string=tig).

**Comment by jonas** [comment]
Fixed by @rolandwalker in #644 

<img width="1132" alt="screen shot 2017-07-09 at 9 36 57 pm" src="https://user-images.githubusercontent.com/8417/27999791-cd300b92-64ee-11e7-9b66-28dea8a45e88.png">

**Comment by guyzmo** [comment]
yaaay 🙌 thanks ♥ and cheers 🍻

**Comment by s-chizhik** [comment]
Hi. I've faced the same issue too. In my terminal Cyrillic letters are not showing :(

`git log` output
![image](https://user-images.githubusercontent.com/5587936/33436279-44ec6b02-d5ed-11e7-95c2-00412fa0e0b8.png)

`tig` output
![image](https://user-images.githubusercontent.com/5587936/33436257-393d6018-d5ed-11e7-9716-9eb8ffec53ec.png)

My configuration

    $ tig --version
    tig version 2.3.0
    $ ncurses5-config --version
    6.0.20160213
    $ ldd /tmp/tig/src/tig
        linux-vdso.so.1 =>  (0x00007ffe0a064000)
        libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007f5704e37000)
        libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007f5704c08000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f57049de000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5704614000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5704410000)
        /lib64/ld-linux-x86-64.so.2 (0x000055a86b9c5000)

Can I provide you any other info? Thanks in advance.
