### ISSUE TITLE
%(file) references the relative filepath to the git root directory, instead of the current directory

### ISSUE THREAD

**Issue by edi9999** [jonas/tig#412]
If you run tig inside `repo/subfolder`

And have a file called `repo/debug.log` 

and run for example `rm %(file)` , It won't be working because it will run `rm debug.log` with the working directory `repo/subfolder` 

Best

**Comment by vivien** [comment]
Hi @edi9999,

I'm not sure if `%(file)` should include `git rev-parse --show-cdup` on assignment, or if we should expose a new `%(cdup)` variable. I'm not aware of the consequences of such a change.

**Comment by edi9999** [comment]
Or it could be something like %(fileabsolute) that would print the absolute path of that file

**Comment by jonas** [comment]
@edi9999 Is this the status view?

@vivien Would it make sense if views tied to the repo root should execute commands from the root? It would still make sense to expose a `%(cdup)` (as well as other repo state variables).

**Comment by jonas** [comment]
I decided to just go ahead and make the expected behaviour for this issue the default, since I think it is how it should be. Initially, Tig had a preference for being subdirectory-aware but has slowly changed to be repo-aware, most recently (if I recall correctly) with the status view listing changes for the whole repo and not just in the directory where Tig was started.

**Comment by edi9999** [comment]
> @edi9999 Is this the status view?

yes indeed

Thanks for the change, it is working as expected now. I also think it is a good default to show the whole repository instead of just the subdirectory you are in

**Comment by vivien** [comment]
It makes sense indeed :+1:
