### ISSUE TITLE
Multiple timezones in git log

### ISSUE THREAD

**Issue by fgrosse** [jonas/tig#428]
When I have a repository where the commit timestamps come from different timezones the git log shown by tig get pretty confusing since it omits the time zones.

Could we somehow unify all show times to the users time zone (`git log --date=local`) ?

**Comment by jonas** [comment]
`set main-view-date = local` works similar to `git-log`'s `--date=local`. There's not currently an option to set all times to the users time zone.

**Comment by eraoul** [comment]
This is still broken. I just wasted a day debugging something complex because I didn't notice that the one key commit was in a different timezone.

What a joke. Git is so user-hostile, and for some reason people seem to love how terrible it is since it lets them seem smart at work when working around its horrible developer experience.

**Comment by PaulChanHK** [comment]
It can work either ways:
1. run command "set main-view-date-use-author = no" inside tig (enter it after pressing colon key)
2. put that line into ~/.tigrc
