### ISSUE TITLE
Feature Request: add support for emojis shortnames in commit messages

### ISSUE THREAD

**Issue by yuchi** [jonas/tig#551]
Ok, they looks stupid. But some people like them (I am more or less among those).

**Comment by jonas** [comment]
What is an "emoji shortname"? I am not sure what is the purpose of this feature.

**Comment by yuchi** [comment]
`:robot:` becomes :robot:

They are used at the start of commit messages as tags.

**Comment by spytheman** [comment]
@yuchi What font which supports emojis, do you use for your terminal ?

**Comment by yuchi** [comment]
In OS X iTerm switches to the system default for emojis. I honestly have no idea of support on other platforms.

**Comment by yuchi** [comment]
To see this trend in the wild you can have a look at commits in The Atom editor (https://github.com/atom/atom/commits/master)

**Comment by jonas** [comment]
Converting `:robot:` to an emoji is out of scope for this project. Maybe this can be implemented via an external script/text preprocessor once I get around to add support for that.

It is unfortunate that emojis themselves are not really supported by Tig. I am not sure where this is breaking. The only emoji that I've seen working is ❤️.

**Comment by jonas** [comment]
Emojis are rendered since 800199e47fc8326a4a2ce25f8f3bb91fed2e3fbf. Closing this one as out of scope.

**Comment by theochampion** [comment]
I agree with @sebastianst, gitmojis are becoming popular so I think it's an interesting functionality for TIG

**Comment by yuchi** [comment]
@jonas Would you mind to re-open this issue given the new context? The Gitmoji project reached 6K stars here on GitHub.

**Comment by yuchi** [comment]
Again, @jonas would you reconsider this feature since using emoji shortcodes has become more widespread?

**Comment by codingedgar** [comment]
> Ok, they looks stupid. But some people like them (I am more or less among those).

I never thought I would become a [gitmoji](https://github.com/carloscuesta/gitmoji) lover, but here I'm, requesting this issue to be opened... 🥺 👉👈

**Comment by raabf** [comment]
I would also like to upvote the possibility to interpret emoji codes. However 

> Maybe this can be implemented via an external script/text preprocessor once I get around to add support for that.

I like this idea, which allows to implement the actual functionality outsitde tig (especially if this is out of scope). That might be also important because emojis are standartized, but not their textual codes whose [can differ between platforms](https://emojipedia.org/shortcodes/), which means that we need flexibility here.

By the way, I personally directly use the UTF-8 symbols instead of their textual code in my commit messages, which works fine in GitHub/GitLab and Tig (but most people doesn’t do this):
![2022-02-16_11-46](https://user-images.githubusercontent.com/4788201/154249206-b5cd491f-8f96-4948-8abe-018f9ef3abeb.png)

**Comment by tony** [comment]
@yuchi, @theochampion, @varac, @robvankeilegom, @codingedgar, @kiuKisas, @nilskuhn, @YusukeSano, @UrGuardian4ngel, @raabf

I created #1191 to emphasize the gitmoji aspect.  This has been gnawing at me for years of using `tig(1)` 😆

FYI, It may get closed again, but if you want to make a good case for it, or since its a niche, it may be worth proposing a PR for a mechanism to find/replace patterns in commit message via config.

**Comment by sebastianst** [comment]
I love the idea of extending `tig` with git message _filters/modifiers_. This way, one could achieve gitmoji rendering with a script.
