### ISSUE TITLE
Enforce Screen-redraw on "R" (refresh) when inside tmux?

### ISSUE THREAD

**Issue by matthiasbeyer** [jonas/tig#554]
Hi. I noticed that if I run tig inside tmux, a "R" (refresh) leaves the interface a bit messy. Would be awesome to enforce a ^L (redraw) if I hit "R" and when I'm inside tmux.

Not sure if this is possible via config, if not I'd love to have an option to enforce this. The implementation could simply check whether the "TMUX" environment variable is set and if yes do a redraw.

What do you think?

**Comment by jonas** [comment]
I am not using tmux and don't know why the terminal ends up messy. One possibility would be to allow keys to trigger multiple actions.

**Comment by matthiasbeyer** [comment]
> One possibility would be to allow keys to trigger multiple actions.

That sounds like a nice idea, indeed!

**Comment by koutcher** [comment]
Better fix the root cause. Make sure you have the proper terminal type in TERM variable (should be `screen` for tmux) and a working terminfo description (the one from macOS 10.11 is broken for example). 

To get a working terminfo description:
`$ curl -O https://invisible-island.net/datafiles/current/terminfo.src.gz`
`$ gunzip terminfo.src.gz`
`$ tic -x -o ~/.terminfo -e screen terminfo.src`
