### ISSUE TITLE
diff-highlight does not work when tig is run inside tmux

### ISSUE THREAD

**Issue by danielmanesku** [jonas/tig#559]
Support for [diff-highlight](https://github.com/git/git/tree/v2.3.5/contrib/diff-highlight) was added in tig 2.2.1, but it only works when run directly from terminal (in my case iTerm2) and not when run inside tmux.

Left - when run inside tmux, right - directly from iTerm:
<img width="1161" alt="tig_tmux" src="https://cloud.githubusercontent.com/assets/6186277/21784971/0417402c-d6be-11e6-8199-7331b0d353d6.png">

I can repro this issue with empty tmux.conf (so it does not seem to be a config problem).

Anyone got this to work inside tmux?

**Comment by koutcher** [comment]
Got the same problem with screen and fixed it with:
$ wget http://invisible-island.net/datafiles/current/terminfo.src.gz
$ gunzip terminfo.src.gz
$ mkdir ~/.terminfo
$ tic -o ~/.terminfo -e screen terminfo.src

**Comment by timotheecour** [comment]
`tic -o ~/.terminfo -e tmux terminfo.src` also seems to work for tmux;
but @smancill why close your  PR https://github.com/Homebrew/homebrew-core/pull/18934 ? this workaround is rather ugly (and raises the question for each user trying this: is this safe? will this wreck my system? etc)

**Comment by smancill** [comment]
It was clear that the Homebrew mantainers would not accept the PR, so I just closed it. There is no point arguing with them, [they owe us nothing](https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing).

**Comment by timotheecour** [comment]
@smancill 
> It was clear that the Homebrew mantainers would not accept the PR

hmm, maybe just needed a bit more pushback.
In any case, I'm trying your PR in a tap: https://github.com/timotheecour/homebrew-timutil/blob/master/tmux_tim.rb but it doesn't seem to work:
```
brew install timotheecour/timutil/tmux_tim
$homebrew_D/opt/tmux_tim/bin/tmux -vv -Ltest2 new
```
has same problem as existing tmux (when i remove `~/.terminfo`)
do you have some advice?

**Comment by smancill** [comment]
Ok, I've checked, it still works (you have to make sure the formula is built otherwise the upstream bottles will be downloaded), but then it doesn't work anymore when I have my own `tmux-256color` in `~/.terminfo` or `$TERMINFO`, and there are problems when supporting italics too, and I don't really understand how ncurses work.

I just figured out that I have long settled with this to avoid all the hassle:

    alias tig='TERM=xterm-256color tig'

There are some refresh issues sometimes, but it is not a big deal.

**Comment by koutcher** [comment]
@timotheecour, unless I'm mistaken, from your description you say you are building tmux while @smancill says he is building tig...

@smancill, after you install and build ncurses+tig from Homebrew you shouldn't need ~/.terminfo anymore but if you still need some custom terminfo, then you'd rather use the infocmp and tic commands from /usr/local/opt/ncurses/bin.

**Comment by koutcher** [comment]
It can't work if you force the TERM variable to something which doesn't match you terminal. 

TERM variable before running tmux must match you actual terminal (e.g. `xterm-256color` for macOS Terminal).

Inside tmux TERM is set to `screen` because it's what tmux expects. The terminfo description shipped with the OS is sometimes incorrect (e.g. macOS 10.11, RHEL 4), hence the need to use your own version (if you prefer and have the permission you can fix the one in /usr/share/terminfo).

Anyway, there is nothing that can be done inside Tig, so I close the issue.
