### ISSUE TITLE
Enable signed (-S) commits

### ISSUE THREAD

**Issue by elbenfreund** [jonas/tig#567]
It would be marvelous if tig could support signed commits (``git commit -S``). As far as my research went so far this is not possible right now.

If it would be helpful to elaborate on this please let me know.
One way or the other, thanks to the entire community for such a wonderful tool.

**Comment by jonas** [comment]
Yes, please elaborate. Is this about showing something in the main or diff view?

**Comment by elbenfreund** [comment]
First of: my appologies - my description and title were actually off.
Git allows individual [commits to be signed with a pgp key](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work) for a while now. This is usually done by passing ``-S`` to ``git comit`` after setting up the key in ``gitconfig``.

As far as I can tell commiting staged changes within ``tig`` using ``Shift + c`` does not allow to mimic this behaviour, that is will just issue unsigned commits. 
Am I right in this understanding? And if so, is there a prospect of allowing signed commits from within ``tig`` using ``Shift + c``.

**Comment by jonas** [comment]
You can configure how Tig calls `git commit` via the keybindings. By default it is:

    bind status     C       !git commit

so adding the following to `~/.tigrc` should be close to what you are asking for:

    bind status     C       !git commit -S

Change `status` to `generic` if you want it to work from all views.

**Comment by jonas** [comment]
Closing this since I think this answers your question.

**Comment by elbenfreund** [comment]
Sorry for the delay. This was exactly the answer I was looking for. Thank you very much - for the help but also the entire project itself. It is much appreciated.

**Comment by jonas** [comment]
You're welcome

**Comment by specious** [comment]
I've got tig 2.3.2, and after adding the following to my `~/.tigrc` I see PGP signatures both when I do `tig log` and when viewing commit details in `tig` proper:

```
set log-options = --show-signature
set diff-options = --show-signature
```

**Comment by tuannvm** [comment]
This works for me:

Edit `~/.tigrc`

```bash
bind status C !git commit --signoff
```

**Comment by pomozoff** [comment]
```bash
bind status     C       !git commit -S
```

Doesn't work for me.
But when I run the command `git commit -S` from the shell I can see the gpg pop-up asking me a pin.
What should I change in the `.tigrc` to sign commits?

**Comment by Django-BOfH** [comment]
HI Anton,

> Doesn't work for me.
> But when I run the command `git commit -S` from the shell I can see the gpg pop-up asking me a pin.
> What should I change in the `.tigrc` to sign commits?

Why are you won't use standard signing option inside git:
  $ git config --local commit.gpgsign true

As described here:
https://dokuwiki.nausch.org/doku.php/nitrokey:arch:start#git_konfigurieren

BTW: Yes, adding a PGP signature to commits or tags is certainly a good 
and valid idea. However, this is of little use if not all participants 
understand and internalize why this should be integrated and implemented 
in the standard workflows. To do this, it is important that, on the one 
hand, all team members have a current and usable PGP key and have 
configured their local Git environment accordingly so that all their 
commits are automatically signed.


ttyl
-- 
Django (Bastard Operator from Hell [BOfH])
aka Michael Nausch
Gänsbrunnenweg 6
85652 Pliening

Tel.: 08121 883176
Fax.: 08121 883179
Mail: ***@***.***>

https://wetterstation-pliening.info
https://ebersberger-liedersammlung.de
https://dokuwiki.nausch.org
