### ISSUE TITLE
Is possible files multiple seletion in status view?

### ISSUE THREAD

**Issue by rainyseason** [jonas/tig#571]
Thanks for the excellent tool :)

for example,
1. mark file that located current cursor by pressing specific key
2. move cursor to other file you want to mark and then step1 
3. pressing key 'u'
4. marked file will be updated at the same time.

**Comment by jonas** [comment]
No this is not possible and I am not sure I understand why you want to "atomically" update a selection of files at the same time.

**Comment by albasili** [comment]
I have one use case: I'm sshfs mounting a remote disk on my machine in order to work when I'm outside of the company network but still inside a VPN. This network connection is actually not extremely efficient and if I need to mark one file at a time I will need to perform multiple network operations which is slowing down considerably the use of the tool, it is eventually more efficient to use git commandline and some shell-fu to select the list of files we want to mark.

Should tig allow multiple selection it would be much faster. If it takes me 3 seconds to stage a file and I have 10 files, i will spend half a minute for something than could potentially take only 3 seconds plus the overhead of selecting the files (which shouldn't be huge).

I hope the usecase is clear enough and I thank you again for this great tool!
