### ISSUE TITLE
Leave prompt with <Escape>

### ISSUE THREAD

**Issue by 0ax1** [jonas/tig#582]
After entering the prompt with `:` or searching with `/`, is there a way to abort the command?
I expected being able to escape the prompt by pressing `<Escape>`.

**Comment by commonquail** [comment]
I wonder if this is possible with readline. If you open the file finder (`f`), which doesn't use readline, you can see that Escape already bails. If you compile without readline support the other prompts will, too. You'd need to configure readline's keybindings, defined in `~/.inputrc` or `/etc/inputrc`. For instance, if you add `ESC: "foo"`, hitting Escape in one of the readline prompts will insert the text `foo`. Unfortunately you can't bind one key to multiple commands and there is no built-in "discard all text *and* submit" command. I managed to hack one together with `ESC: "\C-U\C-K\C-M"
"` (Emacs bindings for: `unix-line-discard`, `kill-line`, `accept-line`), because you *can* bind to multiple *key bindings*; that actually worked but revealed another flaw: arrow keys also send ESC, so mapping only ESC to anything effectively breaks arrow keys in prompts. And even if that had worked, that configuration would probably be shared with any other tool using readline.

**Comment by zhengpd** [comment]
+1 for this. As a nvim user, it feels more intuitive to leave prompt with <Esc>.

**Comment by Vampire** [comment]
If ever implemented, also Backspace would be nice to abort additionally when at the start of the line after the `:` or `/` or similar.

**Comment by towry** [comment]
@0ax1 Why closing this, all other similar issues redirect to this one.
