### ISSUE TITLE
Confusing commit-title-graph option

### ISSUE THREAD

**Issue by andreas-gruenbacher** [jonas/tig#879]
The commit-title-graph option is somewhat confusing: when switching the way how graphs are rendered with ':toggle commit-title-graph' or with the default bindings, 'G', the new setting is shown as 'set commit-title-graph = v1' and similar in the status line. However, the command ':set commit-title-graph = v1' doesn't work ('Unknown option name: commit-title-graph'). Instead, 'set main-view-commit-title-graph = v1' must be used as a command or in config file. This also isn't obvious from the documentation.

**Comment by stevenyvr987** [comment]
I also find it confusing between what is shown and what needs to be typed on the prompt line. The confusion is the same for any toggle option. A toggle option should be prefixed by a view name to be well-defined. The documentation mentions it in the 3rd paragraph of `View settings` of the man page `tigrc`:

> Specifications can also be given for a single column, for example to override the defaults in the system tigrc file. To override a single column, use the column name as a suffix after the view setting name, e.g. main-view-date will allow to set the date in the main view.


The code for showing a new setting is in the function `prompt_toggle_option()`. It could be modified to show, for example, `:set main-view-commit-title-graph = v1` instead of `set main-view-commit-title-graph = v1`. I suggest including a colon so that what is shown mimics exactly what needs to be typed on the prompt line. I'll submit a PR for this effect.
